INSERT INTO public.aaaaccount(account_id,login_id,service_id,accountprofile_id,createdtime), values(301,301,1,2,1674636901189);
INSERT INTO public.aaaaccountstatus(account_id,expireat,afterexp_login,status,updatedtime), values(301,-1,0,NEW,1674636901189);
INSERT INTO public.aaaaccpassword(account_id,password_id), values(301,301);
INSERT INTO public.aaaaccsession(session_id,account_id,user_host,application_host,opentime,closetime,status,user_host_name,authenticator), values(1,2,79.148.128.28,89.140.72.212,1674636673165,1674637013611,CLOSED,79.148.128.28,RememberMeLoginModule);
INSERT INTO public.aaacontactinfo(contactinfo_id,emailid,landline,mobile,fax,web_url,res_phone), values(301,abc@abc.com,652,654,\N,\N,\N);
INSERT INTO public.aaalogin(login_id,user_id,name,domainname), values(301,301,cout112,-);
INSERT INTO public.aaapassword(password_id,password,algorithm,salt,passwdprofile_id,passwdrule_id,createdtime,factor), values(2,$2a$12$BYGhmiqLHPxH6epxIvl.tOfjq5aiHPND8Ig0mY2h8Agwd/Oq46Gni,bcrypt,\\xc30c04090102c4367dcfdbb24e8dd24e0117710c7dd7f03f004cde95c57b1b46d46c9dbb6f8eba23d1ee5bcd71c61f55eb950b65e3b4734c3c5839ee25452c1b381097ec1a3c9545fd5b1de487593fedb169ae65f789241bd503895df8e5,2,1,1674636674057,12);
INSERT INTO public.aaapassword(password_id,password,algorithm,salt,passwdprofile_id,passwdrule_id,createdtime,factor), values(301,$2a$12$kh6OLsMyw5KN0Q4f.bNi0OP0Q1ZsSQAzPTxJI0DDRSlV7w5ui6fmq,bcrypt,\\xc30c040901028bbeac575cfc13fad24e014544e9f4cbe91ea19754f073a682f6d642ca1875012dd5c1267bd1c1ed9bf63deacfbc1fe9f7db6bbf4ff2524891ec09a6cd5610986667888791783d25fe04aa9baabd9673bbb57b61a268c24f,2,1,1674636901189,\N);
INSERT INTO public.aaapasswordstatus(password_id,expireat,afterexp_login,status,updatedtime,change_pwd_on_login), values(2,1682372064059,0,ACTIVE,1674636672937,f);
INSERT INTO public.aaapasswordstatus(password_id,expireat,afterexp_login,status,updatedtime,change_pwd_on_login), values(301,1682412901706,0,NEW,1674636901189,f);
INSERT INTO public.aaauser(user_id,first_name,middle_name,last_name,createdtime,description), values(301,Carlos MF Gabilondo,\N,\N,1674636901189,Some description about a god);
INSERT INTO public.aaausercontactinfo(user_id,contactinfo_id), values(301,301);
INSERT INTO public.aaauserstatus(user_id,status,updatedtime), values(301,ACTIVE,1674636901189);
INSERT INTO public.baseelement(ciid,impactid), values(301,1);
INSERT INTO public.ci(ciid,citypeid,ciname,description,label,createddate,lastmodified,version,lifecyclegroupidentifier,siteid,statusid,helpdeskid), values(301,3,Carlos MF Gabilondo,Some description about a god,\N,\N,\N,\N,\N,\N,\N,1);
INSERT INTO public.cirelationships(cirelationshipid,ciid,ciid2,relationshiptypeid,attributetablename,relationshipid,relationshiptext), values(1,301,16,22,\N,2,USER_DEPARTMENT);
INSERT INTO public.cirelationships(cirelationshipid,ciid,ciid2,relationshiptypeid,attributetablename,relationshipid,relationshiptext), values(2,16,301,21,\N,1,USER_DEPARTMENT);
INSERT INTO public.cirelationshipshierarchy(cirelationshipid,cirelationshipid2), values(1,2);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(295,TECHAUTOASSIGN,CONSIDER_STOPTIMER,TRUE,Consider Only StopTimer is false status as load to technician,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(432,Request_Move,Move_Max_Limit,25,Configuration for Move Tickets max_limit,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(106,RedisCache,REDIS_PASSWORD,H4sIAAAAAAAAAEs1NzNIMko00zVKSUrSNTE1MNS1TEox0TWxMDE1NTExMEkzNgYA7+bLeSQAAAA=,Password To Connect Redis,\N);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(7,Server_StartUp,ISFIRSTLOGIN,false,To Show the Set Up wizard page for the first login,\N);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(604,Server_Startup,Last_Start_Time,1674636693097,\N,\N);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(337,APPROVAL_REMINDER,DaysToTakeAction,2,If configured days exceeds an approval reminder notification sent to the approver,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(338,APPROVAL_REMINDER,ISENABLED,true,To Enable/Disable Approval reminder notification sent to the approver,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(339,APPROVAL_REMINDER,ScheduleTime,600,Configured time for Approval Reminder Schedule time in minutes,\N);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(340,APPROVAL_REMINDER,NotificationLimit,3,Notification Count to sent approval reminder notification for pending approvals,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(352,TRASHED_REQUEST,DELETION_TIME_LIMIT,1,This entry is used for specifying the time limit in days for trashed requests,\N);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(353,APPROVAL_CLARIFICATION_REMINDER,DaysToTakeAction,2,If configured days exceeds an approval clarification reminder notification sent to the user,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(354,APPROVAL_CLARIFICATION_REMINDER,ISENABLED,true,To Enable/Disable Approval clarification reminder notification sent to the user,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(355,APPROVAL_CLARIFICATION_REMINDER,NotificationLimit,3,Notification Count to sent approval clarification reminder notification for pending clarification approvals,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(362,CMDBFeatures,EnableCMDBAPIForTechORReqLogin,,To Enable/Disable cmdb api in technician/Requester login. Possible values Requester,Technician,\N);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(370,SSP,SHOW_VIDEO_TO_USER,true,Configuration for showing Self service portal video to user. Allowed Values:true,false,\N);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(424,ApprovalEmailReplyAction,Approval_Request,Alternatively, you can reply to this email with your decision in the first line of the message. The request approval will be accordingly processed.,,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(425,ApprovalEmailReplyAction,Approval_Change,Alternatively, you can reply to this email with your decision in the first line of the message. The change request approval will be accordingly processed.,,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(426,ApprovalEmailReplyAction,POPendingApprovalNotification,Alternatively, you can reply to this email with your decision in the first line of the message. The purchase order approval will be accordingly processed.,,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(427,ApprovalEmailReplyAction,PRPendingApprovalNotification,Alternatively, you can reply to this email with your decision in the first line of the message. The purchase request approval will be accordingly processed.,,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(428,ApprovalEmailReplyAction,Approval_Release,Alternatively, you can reply to this email with your decision in the first line of the message. The release approval will be accordingly processed.,,1);
INSERT INTO public.globalconfig(globalconfigid,category,parameter,paramvalue,description,helpdeskid), values(901,SOFTWARE,IsCleanSoftwareCIsDone,true,\N,\N);
INSERT INTO public.people(ciid), values(301);
INSERT INTO public.poapproverdetails(approverid,approver,ceilinglimit,ccid,approverstatus,description,helpdeskid), values(301,301,-1,\N,t,\N,1);
INSERT INTO public.portalusers(id,userid,status,ciid,costperhour,helpdeskid), values(301,301,ACTIVE,301,25,1);
INSERT INTO public.recentitems(itemid,url,displaystr,userid,date,modulename,image,detailid,helpdeskid), values(1,SetUpWizard.do?forwardTo=requester&isUser=true&viewType=detail&userId=301,Carlos MF Gabilondo,5,1674637013475,AdminUser,\N,301,1);
INSERT INTO public.requesteremailids(maillistid,userid,emailid), values(1,301,secondary@sec.com);
INSERT INTO public.sdauthorizedrole(sdroleid,account_id,role_id,helpdeskid), values(301,301,29,1);
INSERT INTO public.sduser(userid,employeeid,jobtitle,status,smsmailid,domain_id,secondemailid,ldap_id,user_dn,reportingto,isvipuser,firstname,middlename,lastname,is_in_ad,deleted_by,deleted_time,file_protect_password,typeid,created_by,extension,enabletelephony,sipuser), values(301,45,Master of the universe,ACTIVE,654@dg.com,\N,\N,\N,\N,5,t,Carlos,MF,Gabilondo,\N,\N,\N,\N,1,5,\N,f,\N);
INSERT INTO public.sduserprojectroles(id,userid,projectroleid,helpdeskid), values(301,301,3,1);
INSERT INTO public.srapproverdetails(id,approver,costlimitupto,ccid,approverstatus,description,helpdeskid), values(301,301,0,\N,t,\N,1);
INSERT INTO public.userdepartment(userid,deptid), values(301,5);
INSERT INTO public.userdepthistory(historyid,userid,deptid,editmode,operationtime,updatedby,helpdeskid), values(1,301,\N,sdp.history.manual,1674636901744,5,\N);
INSERT INTO public.userdepthistorydetails(udhistoryid,historyid,tablename,attribute,conversiontype,newvalue,oldvalue,primarykey,operation,additionalinfo,helpdeskid), values(1,1,User,added,-,-,-,-,1,Carlos MF Gabilondo,\N);
INSERT INTO public.usermanager(usermanagerid,userid,managerrole,helpdeskid), values(1,301,1,1);
INSERT INTO public.userpersonalize(personalizeid,personalizekey,personalizeddata,createdby,helpdeskid), values(1,admin_json_5,"new",5,1);
INSERT INTO public.userpersonalize(personalizeid,personalizekey,personalizeddata,createdby,helpdeskid), values(2,OD_AVAILABLE_BANNER_5,{"DONT_SHOW":true},5,\N);
